# DOCSUB_START default_policy_example
id: default_policy_id
policy_version: 1
schema_version: 0.1.0
whylabs_dataset_id: default
org_id: default

metrics:
  - metric: prompt.stats.token_count
  - metric: prompt.stats.char_count
  - metric: response.stats.token_count
  - metric: response.sentiment.sentiment_score

validators:
  - validator: constraint
    options:
      target_metric: response.stats.token_count
      upper_threshold: 10

  - validator: constraint
    options:
      target_metric: response.sentiment.sentiment_score
      upper_threshold: 0
# DOCSUB_END
