whylabs_dataset_id: model-62
policy: my_new_policy
id: 9294f3fa-4f4b-4363-9397-87d3499fce28
policy_version: "1"
schema_version: 0.0.1

# What are the rules for the prompt and response validations
rules:
  prompt:
    - module: sentiment
      lower_threshold: 0.0

    - module: textstat
      metric: character_count
      upper_threshold: 200
      lower_threshold: 2

    - module: toxicity
      upper_threshold: 0.7

  response:
    - module: toxicity
      upper_threshold: 0.9

    - module: input_output
      upper_threshold: 0.5

# Which of the langkit modules you want to use for profiling
profiling:
  - toxicity
  - regexes
  # - all # -> in case you wish to profile all available modules from langkit
