name: Workflow

on:
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Build and run all tests and checks
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.10.8"

      - uses: Gr1N/setup-poetry@v8
        name: Install poetry
        with:
          poetry-version: 1.7.1

      - name: Install python dependencies
        shell: bash
        run: make install

      - name: Check types
        shell: bash
        run: make lint

      - name: Check formatting
        shell: bash
        run: make format

      # Complicted Docker logic to get around disk space issues on github builders
      - name: Remove python dependencies to save space
        if: ${{ inputs.type == 'llm' }}
        shell: bash
        run: |
          rm -rf .venv/
          poetry cache clear PyPI --all
          poetry cache clear torch --all
          echo "Available storage:"
          sudo df -h
          echo

      - name: Create docker dirs
        shell: bash
        run: mkdir -p ${{ inputs.workdir }}/llm/ && mkdir -p ${{ inputs.workdir }}/main/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker container
        run: make build
